Add poetry
dssg/aequitas pull request #193
Opened 2024-05-15 16:08 UTC by valmik-patel

I'm creating this request to start a conversation about adding [Poetry](https://python-poetry.org/) to the project for dependency management.

Poetry allows for easy dependency management while ensuring there are no clashes. I've added the dependencies mentioned in `requirements/management.txt` as dev dependencies to poetry. Dependencies in `requirements/cli.txt` and `requirements/webapp.txt` have been added as optional extras dependencies. And finally, the dependencies in `requirements/main.txt` have been added as the main dependencies for the project.

You can test this locally through the following steps
- Install Poetry 
- Run `poetry install --all-extras` from project root to set up a poetry venv and install all dependencies
- Commands can be run in this venv from project root by adding `poetry run` in front of the command

We can do the following things easily through poetry

- **_Run unit tests_** - We can run unit tests using just a single line of code instead of having to use a script like we currently do. 

`poetry run coverage run -m pytest --cov-report xml:cov.xml --cov-report term`

- **_Build dist files_** - We can easily build dist files using `poetry build`
- **_Publish the package_** - Packages can be published to PyPI using `poetry publish`. This will require [configuring poetry with PyPI credentials](https://python-poetry.org/docs/repositories/).

In addition to all this, we can also automate testing when a PR is made using `GitHub Actions`. Using this method, we can block PRs from being merged if the unit tests fail. `GitHub Actions will also allow us to automatically build and publish packages when a PR is merged. Doing all this setup requires us to add PyPI credentials to GitHub secrets at minimum, and we might need to change some GitHub settings, too.

I wanted to start a conversation using this MR so we can get some opinions from the original maintainers. We will need someone with admin access to the repo to help us add secrets and block PRs from merging when the unit tests fail.

@sgpjesus FYI

2024-05-29 15:08 UTC, sgpjesus commented
Hey @jesteria! Can you give your opinion on changing the setup of aequitas to Poetry? Thank you!

2024-08-21 14:39 UTC, sgpjesus commented on pyproject.toml
> +python = "3.9.16"
I've tried installing on my side, and this was giving trouble, I changed it to: `python = ">=3.8,<4"`, some package had a requirement to be less than python version 4 somehow :sweat_smile:

2024-08-21 14:40 UTC, sgpjesus commented on pyproject.toml
> +version = "0.1.0"
`version = "1.0.0"`

2024-08-21 14:43 UTC, sgpjesus commented on pyproject.toml
> +
```suggestion
[[tool.poetry.source]]
name = "pypi-public"
url = "https://pypi.org/simple/"

```

2024-08-21 14:47 UTC, sgpjesus requested changes
I believe that with the changes I sent, this MR is good to be merged to master. I think we can also drop the previous requirement files.

2024-08-21 20:37 UTC, valmik-patel commented
@sgpjesus I accepted your suggestions and removed the old requirements. Let me know if you need me to do anything else.

2024-08-22 08:23 UTC, sgpjesus commented
@valmik-patel Can you just update the `.lock` file, before merging? I think that will be the last thing! I can't add any commits from my side or else my approval will not be valid for the merge.

2024-08-22 10:10 UTC, sgpjesus approved these changes

2024-08-22 10:11 UTC, sgpjesus commented
I will actually open a new MR to try and relax some of the dependency versions

2024-08-22 10:11 UTC, merged